# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      packages: write

    env:
      # 版本管理
      PROJECT_NAME: 'alinesno-infra-smart-brain-embedding-application'
      PRO_VERSION: '1.0.0-SNAPSHOT'
      CURRENT_PROFIRE: 'dev'
      BUILD_NUMBER: ${{ github.run_number }}

      # 容器镜像
      ALIYUN_CR_REGISTORY: 'registry.cn-shenzhen.aliyuncs.com'
      ALIYUN_CR_NAMESPACE: 'alinesno-infra-platform'

    steps:
      - uses: actions/checkout@v3

      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: 'https://${{ env.ALIYUN_CR_REGISTORY }}'
          username: '${{secrets.ALIYUN_CR_USERNAME}}'
          password: '${{secrets.ALIYUN_CR_PASSWORD}}'

      - name: Deploy to AliyunCR
        run: |
          cd ${{ env.PROJECT_NAME }}
          docker build -t ${{ env.ALIYUN_CR_REGISTORY }}/${{ env.ALIYUN_CR_NAMESPACE }}/${{ env.PROJECT_NAME }}:${{ env.PRO_VERSION }}.${{ env.BUILD_NUMBER }} .
          docker push ${{ env.ALIYUN_CR_REGISTORY }}/${{ env.ALIYUN_CR_NAMESPACE }}/${{ env.PROJECT_NAME }}:${{ env.PRO_VERSION }}.${{ env.BUILD_NUMBER }}

      - name: local remote scp
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.SERVER_BETA_HOST_03 }}
          port: ${{ secrets.SERVER_BETA_PORT_03 }}
          user: ${{ secrets.SERVER_BETA_USER_03 }}
          pass: ${{ secrets.SERVER_BETA_KEY_03 }}
          local: "./deploy/*"
          remote: /home/github-action/${{ env.PROJECT_NAME }}

      - name: SSH Pipelines
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
        with:
          host: ${{ secrets.SERVER_BETA_HOST_03 }}
          port: ${{ secrets.SERVER_BETA_PORT_03 }}
          user: ${{ secrets.SERVER_BETA_USER_03 }}
          pass: ${{ secrets.SERVER_BETA_KEY_03 }}
          connect_timeout: 30s
          script: |
            export PROJECT_NAME=${{ env.PROJECT_NAME }}
            export VERSION=${{ env.PRO_VERSION }}.${{ env.BUILD_NUMBER }}

            export ALIYUN_CR_REGISTORY=${{ env.ALIYUN_CR_REGISTORY }}
            export ALIYUN_CR_NAMESPACE=${{ env.ALIYUN_CR_NAMESPACE }}
            export NAMESPACE=${{ secrets.K8S_NAMESPACE }}

            export CHATGPT_PROXY=${{ secrets.DEV_CHATGPT_PROXY }}
            export CHATGPT_SK=${{ secrets.DEV_CHATGPT_SK }}

            export INFRA_DEV_DOMAIN=${{ secrets.INFRA_BETA_AI_DOMAIN }}

            envsubst < /home/github-action/${{ env.PROJECT_NAME }}/kubernetes-embedding-${{ env.CURRENT_PROFIRE }}.yml | kubectl apply -f -
